# Generated by Django 6.0.6 on 2026-06-21 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghadapi', '0002_alter_person_nin_alter_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugdonation',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drugdonation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drugdonation',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drugdonation',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
