# Generated by Django 6.0.6 on 2026-06-29 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghadapi', '0004_donor_patient_donationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('destroyed', 'Destroyed'), ('maintenance', 'Under Maintenance'), ('assigned', 'Assigned')], default='available', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='machines/')),
            ],
            options={
                'db_table': 'medical_machine',
            },
        ),
        migrations.CreateModel(
            name='MachineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_assignments', to='ghadapi.person')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ghadapi.machine')),
            ],
            options={
                'db_table': 'machine_assignment',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
