# Generated by Django 6.0.6 on 2026-07-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghadapi', '0005_machine_machineassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
