# Generated by Django 6.0.6 on 2026-07-06 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghadapi', '0007_financialcategory_financialsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ghadapi.department'),
        ),
    ]
