# Generated by Django 6.0.6 on 2026-07-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghadapi', '0008_alter_activity_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['acquisition_date']},
        ),
    ]
