# Generated by Django 6.0.6 on 2026-07-07 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghadapi', '0009_alter_machine_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='machineassignment',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
