# Generated by Django 6.0.6 on 2026-07-08 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghadapi', '0010_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialSettings',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='expensetransaction',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='expensetransaction',
            name='related_distribution',
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='related_donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transaction', to='ghadapi.drugdonation'),
        ),
    ]
