# Generated by Django 6.0.6 on 2026-07-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghadapi', '0011_delete_financialsettings_remove_donation_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
