# Generated by Django 6.0.6 on 2026-07-16 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghadapi', '0013_user_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarmWinterDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warm_winter_donations', to='ghadapi.person')),
            ],
            options={
                'db_table': 'warm_winter_donation',
                'ordering': ['-date'],
            },
        ),
    ]
