# Generated by Django 6.0.6 on 2026-07-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghadapi', '0014_warmwinterdonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('mandate', models.CharField(blank=True, max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_memberships', to='ghadapi.person')),
            ],
            options={
                'ordering': ['mandate', 'person__last_name', 'person__first_name'],
            },
        ),
    ]
