# Generated by Django 6.0.6 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghadapi', '0015_officemember'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='officemember',
            constraint=models.UniqueConstraint(fields=('person', 'mandate'), name='unique_office_member_per_mandate'),
        ),
    ]
